name: Auto Update Changelog

on:
  push:
    branches:
      - changelog-test
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags and history are fetched

      - name: Get Latest and Next Stable Tag
        id: version
        run: |
          # Get the latest stable version
          latest_stable=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)

          # Get the next major or minor version
          dev_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+-dev.[0-9]+$' | head -n 1)
          next_stable=$(echo "$dev_tag" | sed -E 's/-dev.[0-9]+$//')
          next_version=$(echo "$next_stable" | sed -E 's/v//')

          echo "LATEST_STABLE=$latest_stable" >> $GITHUB_ENV
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      - name: Get CommitId by Tag
        id: get_commitid_by_tag
        run: |
          # Fetch all tags including dev and stable
          commitId=$(git rev-list -n 1 ${{ env.LATEST_STABLE }})

          echo "commitId=$commitId" >> $GITHUB_ENV

      - name: Update Changelogs
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -- ${{ env.commitId }}..HEAD
        env:
          OUTPUT: CHANGELOG_LATEST.md

      - name: Prepend to CHANGELOG.md
        run: |
          awk -v f1="CHANGELOG_LATEST.md" '
          BEGIN {
              while ((getline line < f1) > 0) {
                  content = content line "\n"
              }
              close(f1)
          }
          {
              if (!inserted && $0 ~ /^## \[/) {
                  print content
                  inserted = 1
              }
              print
          }' CHANGELOG.md > temp_file && mv temp_file CHANGELOG.md

      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG for ${{ env.NEXT_VERSION }}" || echo "No changes to commit"
          git push origin ${{ github.ref_name }} || echo "No changes to push"
