name: Auto Update Changelog

on:
  push:
    branches:
      - changelog-test
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags and history are fetched

      - name: Get CommitId by Tag
        id: get_commitid_by_tag
        run: |
          # Fetch all tags including dev and stable
          commitId=$(git rev-list -n 1 v3.1.1)

          echo "commitId=$commitId" >> $GITHUB_ENV

      - name: Update Changelogs
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -- ${{ env.commitId }}..HEAD --prepend CHANGELOG.md

      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG" || echo "No changes to commit"
          git push origin ${{ github.ref_name }} || echo "No changes to push"
