name: Generate Changelog

on:
  push:
    branches:
      - changelog-test  # or the default branch of your project

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Rust (for git-cliff)
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Generate changelog
        run: git-cliff

      - name: Commit and push changelog
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
