name: Auto Update Changelog

on:
  push:
    branches:
      - changelog-test
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.8.0/git-cliff-2.8.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          mv git-cliff-2.8.0/git-cliff /usr/local/bin

      - name: Get All Tags
        id: get_all_tags
        run: |
          # Fetch all tags including dev and stable
          git fetch --tags

          # List all tags and store in an environment variable
          {
            echo "tags<<EOF"
            git tag -l
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Calculate Next Version
        id: next_version
        run: |
          # Get the latest version tag, excluding dev tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Parse the latest version number (ignore 'dev' tags for increment)
          latest="${latest_tag//-dev.*/}"  # Remove the leading '-dev'
          latest="${latest_tag//$v/}"  # Remove the leading 'v'
          IFS='.' read -r -a parts <<< "$latest"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}

          new_version="v$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Merge Changelog for All Tags
        run: |
          # Generate changelog, skipping 'dev' tags and focusing on commits
          git-cliff --unreleased --tag="${{ env.tags }}" --tag-pattern="^v?(\\d+\\.\\d+\\.\\d+)" --prepend CHANGELOG.md


      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG" || echo "No changes to commit"
          git push origin changelog-test || echo "No changes to push"
