name: Auto Update Changelog

on:
  push:
    branches:
      - changelog-test
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.8.0/git-cliff-2.8.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          mv git-cliff-2.8.0/git-cliff /usr/local/bin

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate Next Version
        id: next_version
        run: |
          latest="${{ env.latest_tag }}"
          IFS='.' read -r -a parts <<< "${latest//v/}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          new_version="v$major.$minor.$((patch + 1))"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Generate Changelog
        run: git-cliff --unreleased --tag "${{ env.new_version }}" --prepend CHANGELOG.md

      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG" || echo "No changes to commit"
          git push origin changelog-test || echo "No changes to push"
