name: Auto Update Changelog

on:
  push:
    branches:
      - changelog-test
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.8.0/git-cliff-2.8.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          mv git-cliff-2.8.0/git-cliff /usr/local/bin

      - name: Get CommitId by Tag
        id: get_commitid_by_tag
        run: |
          # Fetch all tags including dev and stable
          commitId=$(git rev-list -n 1 v3.1.1)

          echo "commitId=$commitId" >> $GITHUB_ENV

      - name: Update Changelogs
        run: |
          # Generate changelog, skipping 'dev' tags and focusing on commits
          git-cliff --prepend CHANGELOG.md -- ${{ env.commitId }}..HEAD


      - name: Commit & Push Changelog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG" || echo "No changes to commit"
          git push origin changelog-test || echo "No changes to push"
